package com.example.demo.exception;

public enum ErrorCode {
	MEMBER_NOT_FOUND,
    MEMBER_DUPLICATE_USERNAME,
    LOGIN_FAILED,
    PRODUCT_NOT_FOUND,
    PRODUCT_STOCK_NOT_ENOUGH,
    ORDER_NOT_FOUND,
    ORDER_STATUS_INVALID,
    ORDER_CONFLICT,
    VALIDATION_ERROR,
    SYSTEM_ERROR
}
