# 指定 Terraform 版本與 provider 需求
terraform {
  required_version = ">= 1.6.0"

  required_providers {
    # local provider：用來產生本機檔案，不會建立雲端資源，也不會產生費用
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

# local provider 不需要額外設定
provider "local" {}

# 用 Terraform 產生一份本機 staging 環境說明檔
resource "local_file" "staging_environment_doc" {
  filename = "${path.module}/generated-staging-env.md"

  # 🎯 改用 <<-EOT，內部文字前後都留好標準空行
  content = <<-EOT
    # TLBank Staging Environment

    ## Purpose

    This file is generated by Terraform to document the local staging environment.

    ## Application

    - Name: ${var.app_name}
    - Environment: ${var.environment}
    - Backend Port: ${var.backend_port}

    ## Infrastructure Components

    - Spring Boot Backend
    - SQL Server Container
    - Redis Container
    - Docker Compose
    - GitHub Actions CI/CD

    ## Notes

    This Terraform configuration is currently used for IaC validation only.
    It does not create cloud resources and does not generate cloud cost.
  EOT
}