-- V14: Reshape audit_logs for Sprint 9 audit module

DROP TABLE IF EXISTS audit_logs;

CREATE TABLE audit_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(100),
    action              VARCHAR(50)   NOT NULL,
    ip_address          VARCHAR(45),
    result              VARCHAR(20)   NOT NULL,
    detail              VARCHAR(500),
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_username ON audit_logs(username);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);
