-- V2: Card products and features
CREATE TABLE card_products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code        VARCHAR(30)   NOT NULL,
    product_name        VARCHAR(100)  NOT NULL,
    description         VARCHAR(500),
    annual_fee          DECIMAL(12, 2) NOT NULL DEFAULT 0,
    credit_limit_min    DECIMAL(12, 2) NOT NULL,
    credit_limit_max    DECIMAL(12, 2) NOT NULL,
    status              VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_card_products_code UNIQUE (product_code)
);

CREATE TABLE product_features (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT        NOT NULL,
    feature_name        VARCHAR(100)  NOT NULL,
    feature_description VARCHAR(500),
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_features_product FOREIGN KEY (product_id) REFERENCES card_products(id)
);

CREATE INDEX idx_card_products_status ON card_products(status);
