-- V4: OTP records for identity verification
CREATE TABLE otp_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT        NOT NULL,
    otp_code            VARCHAR(10)   NOT NULL,
    purpose             VARCHAR(30)   NOT NULL,
    expired_at          TIMESTAMP     NOT NULL,
    verified            BOOLEAN       NOT NULL DEFAULT FALSE,
    retry_count         INT           NOT NULL DEFAULT 0,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_otp_records_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_otp_records_user_purpose ON otp_records(user_id, purpose);
