-- V5: Review cases and remarks
CREATE TABLE review_cases (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id      BIGINT        NOT NULL,
    reviewer_id         BIGINT,
    status              VARCHAR(30)   NOT NULL DEFAULT 'PENDING',
    assigned_at         TIMESTAMP,
    completed_at        TIMESTAMP,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_review_cases_application UNIQUE (application_id),
    CONSTRAINT fk_review_cases_application FOREIGN KEY (application_id) REFERENCES applications(id),
    CONSTRAINT fk_review_cases_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id)
);

CREATE TABLE review_remarks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_case_id      BIGINT        NOT NULL,
    remark              VARCHAR(1000) NOT NULL,
    created_by          BIGINT        NOT NULL,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_remarks_case FOREIGN KEY (review_case_id) REFERENCES review_cases(id),
    CONSTRAINT fk_review_remarks_user FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_review_cases_status ON review_cases(status);
