-- V6: Audit logs
CREATE TABLE audit_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type         VARCHAR(50)   NOT NULL,
    entity_id           VARCHAR(50)   NOT NULL,
    action              VARCHAR(50)   NOT NULL,
    performed_by        BIGINT,
    details             VARCHAR(2000),
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (performed_by) REFERENCES users(id)
);

CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);
