-- V7: System parameters
CREATE TABLE system_parameters (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    param_key           VARCHAR(100)  NOT NULL,
    param_value         VARCHAR(500)  NOT NULL,
    description         VARCHAR(500),
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_system_parameters_key UNIQUE (param_key)
);
